### ISSUE TITLE
The problem of environment

### ISSUE THREAD

**Issue by Songsongxg** [mishgon/vox2vec#4]
My environment configuration is all right, but it keeps reporting this mistake, asking for help!
The error is :
File "/root/anaconda3/envs/sxg/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'pdp.interface.TransformerDescription'>: attribute lookup TransformerDescription on pdp.interface failed

**Comment by mishgon** [comment]
Dear @Songsongxg,

Thank you for the issue! I suppose the easiest way to fix your problem is to get rid of pdp library in the dependencies. Please, give me a few hours, I'll do that.

**Comment by Songsongxg** [comment]
Dear @mishgon ，
Thank you very much for your reply！ Have you found a solution? I need it so much.

**Comment by mishgon** [comment]
Dear @Songsongxg,

I have removed the pdp dependency. Give this a try :)

By the way, let me ask you, how are you going to use vox2vec? Are you going to reproduce the whole pre-training pipeline (e.g. for further modification) or you are just interested in using the already pre-trained vox2vec?

**Comment by Songsongxg** [comment]
Dear @mishgon ,
Is deleting the pdp  dependency just removing pdp in the environment? Whether the code section needs to be modified?

If possible, I will make further changes to vox2vec to make it work better. Of course, I am also very grateful for the code you provided.

**Comment by mishgon** [comment]
Just update the repo (pull the most recent commit from the remote), and try to run the scripts :)
If you have installed the project with `pip install -e .` command, you don't have to reinstall it after pulling updates.
